name: CI/CD Pipeline Docker

on: 
 push:
  branches: ["main"]
  
jobs:
 build-and-test:
  runs-on: ubuntu-latest

 steps:
  - name: Checkout do código
    uses: actions/Checkout@v3

  - name: Testar build da Imagem Docker
    run: docker build -t meu-catalogo-app .       